name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: 2570
          password: Chaurionde1!
#           password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:


          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: 2570/hetic_devops_data:latest
#           tags: 2570/hetic_devops_data:${{ steps.vars.outputs.sha_short }}
          # build on feature branches, push only on main branch
          push: true # ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Trigger train
        run: |
          curl -H "Authorization: token ${{ secrets.trigger_ML_pipeline  }}" \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          "https://api.github.com/repos/adriendemaegdt/devops_train/dispatches" \
          -d '{"event_type": "new_dataset_latest", "client_payload": {"dataset_commit_id":latest}}'
          
#     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
# -d '{"event_type": "new_dataset_${{ steps.vars.outputs.sha_short }}", "client_payload": {"dataset_commit_id":latest}}'
